name = "CompileIQ"
uuid = "4b2b6ecf-6568-42de-a118-30d12bf9bad6"
authors = ["AntonOresten <antonoresten@proton.me> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
